depends: fix macOS cross build failures
Building on systems which have a newer GCC (15+), requires additional
includes to be patched into libtapi. The missing includes cause libtapi
detection to fail, when building cctools which ultimately results in not
being able to link against the macOS SDK.

```bash
configure:18786: checking tapi/tapi.h and libtapi support
configure:18811: /root/bitcoin/depends/arm64-apple-darwin/native/bin/clang++ -o conftest -O3 -std=c++1z -isystem /usr/local/include -isystem /usr/pkg/include  -DLD64_VERSION_NUM=711 -fblocks -D__arm64__    -I/root/bitcoin/depends/arm64-apple-darwin/native/include   -L/root/bitcoin/depends/arm64-apple-darwin/native/lib -Wl,-rpath=\$$ORIGIN/../lib -L/usr/local/lib -L/usr/pkg/lib  conftest.cpp  -ltapi >&5
In file included from conftest.cpp:34:
In file included from /root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/tapi.h:26:
/root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/LinkerInterfaceFile.h:178:58: error: unknown type name 'uint8_t'
  178 |   static bool isSupported(const std::string &path, const uint8_t *data,
      |                                                          ^
/root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/LinkerInterfaceFile.h:228:41: error: unknown type name 'uint8_t'
  228 |   create(const std::string &path, const uint8_t *data, size_t size,
      |                                         ^
/root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/LinkerInterfaceFile.h:254:41: error: unknown type name 'uint8_t'
  254 |   create(const std::string &path, const uint8_t *data, size_t size,
      |                                         ^
/root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/LinkerInterfaceFile.h:294:21: error: use of undeclared identifier 'uint32_t'
  294 |   const std::vector<uint32_t> &getPlatformSet() const noexcept;
      |                     ^
In file included from conftest.cpp:34:
In file included from /root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/tapi.h:27:
/root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/PackedVersion32.h:40:3: error: unknown type name 'uint32_t'
   40 |   uint32_t _version;
      |   ^
/root/bitcoin/depends/arm64-apple-darwin/native/include/tapi/PackedVersion32.h:53:19: error: unknown type name 'uint32_t'
   53 |   PackedVersion32(uint32_t rawVersion) : _version(rawVersion) {}
      |                   ^
6 errors generated.
```